<?php 
require_once("../models/session.php"); 
require_once("../models/database.php"); 
require_once("../models/user.php");
require_once("../models/tack.php");
require_once("../models/board.php");
require_once("../helper/basicHelper.php"); 
require_once("../helper/validationHelper.php"); 
?>